name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  automation-test-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm run ci:test
      - name: Start server and run end-to-end tests
        run: |
          npm run dev &
          npx wait-on http-get://0.0.0.0:5173 --timeout 30000
          npm run e2e
        env:
          CI: true
